[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.124.0",
    "pandas>=2.3.3",
    "pydantic>=2.12.5",
    "ta>=0.11.0",
    "uvicorn>=0.38.0",
    "yfinance>=0.2.66",
]
